apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stonegame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: __BACKEND_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_EXPIRATION
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URI
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15