apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stonegame-virtual-service
  namespace: stonegame
spec:
  hosts:
    - "*"
  gateways:
    - stonegame-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend
            port:
              number: 8080
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
            port:
              number: 80