spring.application.name=stonegame

spring.mongodb.uri=${DB_URI}
spring.mvc.servlet.path=/api

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

info.app.name=stonegame
info.app.description=Stone game backend
info.app.version=0.0.1-SNAPSHOT
